import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from backend.utils.config import settings


def _item_to_md(item: Any) -> str:
    """Coerce any LLM-returned list item to a clean Markdown string."""
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        # Rich finding: {title, description, significance}
        if "title" in item and "description" in item:
            title = item.get("title", "")
            desc = item.get("description", "")
            sig = item.get("significance", "")
            result = f"**{title}**: {desc}"
            if sig:
                result += f" *(Significance: {sig})*"
            return result
        # Simple key:value dict — join non-empty values
        for key in ("point", "text", "content", "finding", "insight", "description"):
            if key in item:
                return str(item[key])
        return " — ".join(str(v) for v in item.values() if v)
    if isinstance(item, (list, tuple)):
        return " | ".join(_item_to_md(x) for x in item)
    return str(item)
from backend.utils.logger import get_logger

logger = get_logger(__name__)


class MarkdownExporter:

    def export(self, query: str, summary: dict, raw_results: list, metadata: dict) -> str:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        safe_name = re.sub(r"[^\w\s-]", "", query[:40]).strip().replace(" ", "_")
        filename = f"report_{safe_name}_{timestamp}.md"

        reports_dir = Path(settings.reports_dir)
        reports_dir.mkdir(parents=True, exist_ok=True)
        filepath = reports_dir / filename

        content = self._build(query, summary, raw_results, metadata, timestamp)
        filepath.write_text(content, encoding="utf-8")

        logger.info(f"[MarkdownExporter] Saved: {filepath}")
        return str(filepath)

    def _build(self, query: str, summary: dict, raw_results: list, metadata: dict, timestamp: str) -> str:
        lines: list[str] = []

        lines.append(f"# Research Report: {query}\n")
        lines.append(f"**Generated:** {timestamp} UTC  ")
        lines.append(f"**Tools Used:** {', '.join(metadata.get('tools_used', []))}  ")
        lines.append(f"**Iterations:** {metadata.get('iterations', 1)}  ")
        lines.append(f"**Sources Collected:** {metadata.get('sources_count', len(raw_results))}\n")
        lines.append("---\n")

        lines.append("## Executive Summary\n")
        lines.append(summary.get("executive_summary", "_No summary available._"))
        lines.append("\n---\n")

        key_points = summary.get("key_points", [])
        if key_points:
            lines.append("## Key Points\n")
            for point in key_points:
                lines.append(f"- {_item_to_md(point)}")
            lines.append("")

        findings = summary.get("important_findings", [])
        if findings:
            lines.append("\n## Important Findings\n")
            for finding in findings:
                lines.append(f"- {_item_to_md(finding)}")
            lines.append("")

        insights = summary.get("actionable_insights", [])
        if insights:
            lines.append("\n## Actionable Insights\n")
            for insight in insights:
                lines.append(f"- {_item_to_md(insight)}")
            lines.append("")

        references = summary.get("references", [])
        if references:
            lines.append("\n## References\n")
            for ref in references:
                if isinstance(ref, dict):
                    title = ref.get("title", "Unknown")
                    url = ref.get("url", "")
                    relevance = ref.get("relevance", "")
                    entry = f"- [{title}]({url})" if url else f"- {title}"
                    if relevance:
                        entry += f" — *{relevance}*"
                    lines.append(entry)
                else:
                    lines.append(f"- {ref}")
            lines.append("")

        lines.append("\n---\n")
        lines.append("*Generated by Autonomous Research Agent*")

        return "\n".join(lines)
